### PR TITLE
Fix host key validation

### PR DESCRIPTION
**Pull request by MightyMoud**
Fix the host key validation on the SSH config 🤦🏼‍♂️

- Use `ssh-scan` before first connection to grab host public key and store it in `known_hosts`
- Use knownhosts callback to confirm the public key before allowing the connection

### CODE REVIEW

**Comment by DanielleMaywood** [comment]
`ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts` 

This _probably_ isn't the best idea. This is because it doesn't give the user the chance to check that the public key is what they were expecting. So in the event that there is a MITM attack at the time of `init` then they would be completely unaware.

The practice that openssh does is add a prompt in the CLI to ask the user if they are okay with the key.

```
The authenticity of host 'hostname (ip)' can't be established.
ED25519 key fingerprint is SHA256:<the public key>.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

What you can do is either at start or on connect show a prompt to the user to confirm that the host key is what they were expecting.

This demonstrates what I mean
https://github.com/skeema/knownhosts?tab=readme-ov-file#writing-new-known_hosts-entries

**Comment by MightyMoud** [comment]
Yeh I see what you mean. I have been focused on making the process smoother. Adding that prompt sucks but is essential.
That being said, I think we can do better than that default prompt which is not very useful in my opinion. 

Let me do some thinking and ticker around

**Comment by MightyMoud** [comment]
Alright, 
I'm happy with this. 
image
My thoughts:
- We can use the ASCII art to show the owner that we are connecting to the right VPS
- I think the default prompt is made for machines, not humans. This prompt I made makes a lot more sense to me
- Originally I was thinking to use the ASCII art to display that every time we login, on `launch` and `deploy` commands and so on - Started thinking that the beauty of SSH is that it just works, and maybe that would be too much information. I'll consider it. Also it seems the library handles the case when the public key of the host changes. So it should cover it without having the user check from memory how the art looks like.


I'm happy with this and it sounds secure enough to me. 
Let me know what you think.

**Comment by DanielleMaywood** [comment]
I'm currently away from a computer so cannot test it but from an overview it looks good to me! Thanks for making this change

**Comment by MightyMoud** [comment]
Thanks @DanielleMaywood! 
I'll probably merge this in tomorrow.
I appreciate your time and efforts so far.

Cheers

**Pull request merged**
